applications:
- api_domain: people-qa.upraise.io
  application_name: upraise
  authentication_mode: non-authenticated
  exclude_paths: []
  target_url: https://sg-forge.atlassian.net/jira/your-work
  type: web
